//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treatment.Pages.Treatment {
    
    
    public partial class Employees {
        
        /// <summary>
        /// Employee_Name_Ar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Employee_Name_Ar;
        
        /// <summary>
        /// RFVtxtEmployee_Name_Ar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RFVtxtEmployee_Name_Ar;
        
        /// <summary>
        /// Employee_Name_En control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Employee_Name_En;
        
        /// <summary>
        /// RequiredFieldValidator1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        
        /// <summary>
        /// Employee_Email control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Employee_Email;
        
        /// <summary>
        /// RequiredFieldValidator2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
        
        /// <summary>
        /// Employee_Password control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Employee_Password;
        
        /// <summary>
        /// RequiredFieldValidator3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
        
        /// <summary>
<<<<<<< Updated upstream
        /// Employee_Phone control.
=======
        /// Emp_Structure control.
>>>>>>> Stashed changes
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< Updated upstream
        protected global::System.Web.UI.WebControls.TextBox Employee_Phone;
=======
        protected global::System.Web.UI.WebControls.ListBox Emp_Structure;
>>>>>>> Stashed changes
        
        /// <summary>
        /// RequiredFieldValidator4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator4;
        
        /// <summary>
<<<<<<< Updated upstream
        /// Active control.
=======
        /// RequiredFieldValidator3 control.
>>>>>>> Stashed changes
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< Updated upstream
        protected global::System.Web.UI.HtmlControls.HtmlInputCheckBox Active;
        
        /// <summary>
        /// ListBox1 control.
=======
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
        
        /// <summary>
        /// Groups control.
>>>>>>> Stashed changes
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< Updated upstream
        protected global::System.Web.UI.WebControls.ListBox ListBox1;
        
        /// <summary>
        /// StructureDataSource control.
=======
        protected global::System.Web.UI.WebControls.DropDownList Groups;
        
        /// <summary>
        /// GroupDataSource control.
>>>>>>> Stashed changes
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< Updated upstream
        protected global::System.Web.UI.WebControls.EntityDataSource StructureDataSource;
        
        /// <summary>
        /// Groups control.
=======
        protected global::System.Web.UI.WebControls.EntityDataSource GroupDataSource;
        
        /// <summary>
        /// Active control.
>>>>>>> Stashed changes
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< Updated upstream
        protected global::System.Web.UI.WebControls.DropDownList Groups;
        
        /// <summary>
        /// GroupDataSource control.
=======
        protected global::System.Web.UI.HtmlControls.HtmlInputCheckBox Active;
        
        /// <summary>
        /// EmpID control.
>>>>>>> Stashed changes
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< Updated upstream
        protected global::System.Web.UI.WebControls.EntityDataSource GroupDataSource;
=======
        protected global::System.Web.UI.WebControls.HiddenField EmpID;
>>>>>>> Stashed changes
        
        /// <summary>
        /// Save control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Save;
        
        /// <summary>
        /// AddEmp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton AddEmp;
        
        /// <summary>
        /// UCard control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl UCard;
    }
}
