
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Treatment.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Assignment_Status
{

    public Assignment_Status()
    {

        this.Treatment_Detial = new HashSet<Treatment_Detial>();

    }


    public int Assignment_Status_Id { get; set; }

    public string Assignment_Status_Name_Ar { get; set; }

    public string Assignment_Status_Name_En { get; set; }



    public virtual ICollection<Treatment_Detial> Treatment_Detial { get; set; }

}

}
