//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treatment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Structure
    {
        public Employee_Structure()
        {
            this.Notification_Master = new HashSet<Notification_Master>();
            this.Notification_Master1 = new HashSet<Notification_Master>();
            this.Treatment_Detial = new HashSet<Treatment_Detial>();
            this.Treatment_Master = new HashSet<Treatment_Master>();
        }
    
        public int Employee_Structure_Id { get; set; }
        public Nullable<int> Structure_Id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public Nullable<bool> Status_Structure { get; set; }
        public Nullable<bool> Default_Structure { get; set; }
        public Nullable<bool> Type_Delegation { get; set; }
        public Nullable<System.DateTime> Date_Delegation { get; set; }
        public Nullable<int> Employee_Delegation { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Structure Structure { get; set; }
        public virtual ICollection<Notification_Master> Notification_Master { get; set; }
        public virtual ICollection<Notification_Master> Notification_Master1 { get; set; }
        public virtual ICollection<Treatment_Detial> Treatment_Detial { get; set; }
        public virtual ICollection<Treatment_Master> Treatment_Master { get; set; }
    }
}
