
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Treatment.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class LanguageMaster
{

    public LanguageMaster()
    {

        this.Lanuage_Detials = new HashSet<Lanuage_Detials>();

    }


    public int ID { get; set; }

    public string Language_Name { get; set; }



    public virtual ICollection<Lanuage_Detials> Lanuage_Detials { get; set; }

}

}
