<<<<<<< HEAD
=======

>>>>>>> 60375737d9c40c1bae275e24705374f6e58986df
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD
namespace Treatment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageMaster
    {
        public LanguageMaster()
        {
            this.Employees = new HashSet<Employee>();
            this.Lanuage_Detials = new HashSet<Lanuage_Detials>();
        }
    
        public int ID { get; set; }
        public string Language_Name { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Lanuage_Detials> Lanuage_Detials { get; set; }
    }
=======

namespace Treatment.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class LanguageMaster
{

    public LanguageMaster()
    {

        this.Lanuage_Detials = new HashSet<Lanuage_Detials>();

    }


    public int ID { get; set; }

    public string Language_Name { get; set; }



    public virtual ICollection<Lanuage_Detials> Lanuage_Detials { get; set; }

}

>>>>>>> 60375737d9c40c1bae275e24705374f6e58986df
}
