<<<<<<< HEAD
=======

>>>>>>> 60375737d9c40c1bae275e24705374f6e58986df
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD
namespace Treatment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lanuage_Detials
    {
        public int Language_Detial_ID { get; set; }
        public Nullable<int> Language_Master_ID { get; set; }
        public string Language_Detial_FieldName { get; set; }
        public string Language_Detial_Value { get; set; }
    
        public virtual LanguageMaster LanguageMaster { get; set; }
    }
=======

namespace Treatment.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Lanuage_Detials
{

    public int Language_Detial_ID { get; set; }

    public Nullable<int> Language_Master_ID { get; set; }

    public string Language_Detial_FieldName { get; set; }

    public string Language_Detial_Value { get; set; }



    public virtual LanguageMaster LanguageMaster { get; set; }

}

>>>>>>> 60375737d9c40c1bae275e24705374f6e58986df
}
