//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treatment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_File
    {
        public int Log_Id { get; set; }
        public Nullable<System.DateTime> Log_Date { get; set; }
        public string Log_Note { get; set; }
        public Nullable<int> Login_Id { get; set; }
        public Nullable<int> Form_Id { get; set; }
        public string Log_Name { get; set; }
        public string Log_Description { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Permission Permission { get; set; }
    }
}
