//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treatment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Board_Member
    {
        public M_Board_Member()
        {
            this.M_Attendees = new HashSet<M_Attendees>();
            this.M_Recommendation = new HashSet<M_Recommendation>();
        }
    
        public int Board_Member_Id { get; set; }
        public Nullable<int> Board_Id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public Nullable<int> Member_Type_Id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<M_Attendees> M_Attendees { get; set; }
        public virtual M_Board M_Board { get; set; }
        public virtual M_Member_Type M_Member_Type { get; set; }
        public virtual ICollection<M_Recommendation> M_Recommendation { get; set; }
    }
}
