//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treatment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_M_Attachments
    {
        public int Attachments_Id { get; set; }
        public Nullable<int> Meeting_Id { get; set; }
        public string Path { get; set; }
        public string FileName { get; set; }
    
        public virtual M_Meeting M_Meeting { get; set; }
    }
}
