//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treatment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Meeting
    {
        public M_Meeting()
        {
            this.M_Attendees = new HashSet<M_Attendees>();
            this.M_Recommendation = new HashSet<M_Recommendation>();
            this.M_Topic = new HashSet<M_Topic>();
        }
    
        public int Meeting_Id { get; set; }
        public Nullable<int> Board_Id { get; set; }
        public string Meeting_Name_Ar { get; set; }
        public string Meeting_Name_En { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.DateTime> Meeting_Date { get; set; }
        public Nullable<System.TimeSpan> Meeting_Time { get; set; }
        public Nullable<int> Meeting_Status { get; set; }
        public string Meeting_Minutes { get; set; }
        public Nullable<int> Board_Location_Id { get; set; }
    
        public virtual ICollection<M_Attendees> M_Attendees { get; set; }
        public virtual M_Board M_Board { get; set; }
        public virtual M_Board_Location M_Board_Location { get; set; }
        public virtual ICollection<M_Recommendation> M_Recommendation { get; set; }
        public virtual ICollection<M_Topic> M_Topic { get; set; }
        public virtual M_Meeting_Status M_Meeting_Status { get; set; }
    }
}
