//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treatment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Meeting_Status
    {
        public M_Meeting_Status()
        {
            this.M_Meeting = new HashSet<M_Meeting>();
        }
    
        public int Meeting_Status_Id { get; set; }
        public string Meeting_Status__Name_Ar { get; set; }
        public string Meeting_Status__Name_En { get; set; }
    
        public virtual ICollection<M_Meeting> M_Meeting { get; set; }
    }
}
