//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treatment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Member_Type
    {
        public M_Member_Type()
        {
            this.M_Board_Member = new HashSet<M_Board_Member>();
        }
    
        public int Member_Type_Id { get; set; }
        public string Member_Type_Name_Ar { get; set; }
        public string Member_Type_Name_En { get; set; }
    
        public virtual ICollection<M_Board_Member> M_Board_Member { get; set; }
    }
}
