//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treatment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Topic_Status
    {
        public int M_Topic_Status_Id { get; set; }
        public string M_Topic_Status_Name_Ar { get; set; }
        public string M_Topic_Status_Name_En { get; set; }
    }
}
