//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treatment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification_Employee
    {
        public int NotificationShow_Employee_Id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public Nullable<int> NotificationShow_Id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Notification_Show Notification_Show { get; set; }
    }
}
