//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treatment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification_Show
    {
        public Notification_Show()
        {
            this.Notification_Employee = new HashSet<Notification_Employee>();
            this.Notification_Master = new HashSet<Notification_Master>();
        }
    
        public int Notification_Show_Id { get; set; }
        public string Notification_Show_Name_Ar { get; set; }
        public string Notification_Show_Name_En { get; set; }
    
        public virtual ICollection<Notification_Employee> Notification_Employee { get; set; }
        public virtual ICollection<Notification_Master> Notification_Master { get; set; }
    }
}
