//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treatment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OurSystem
    {
        public OurSystem()
        {
            this.Permissions = new HashSet<Permission>();
        }
    
        public int ID { get; set; }
        public string System_Name_Ar { get; set; }
        public string System_Name_En { get; set; }
    
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}
