
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Treatment.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Permission_Group
{

    public int Permission_Group_Id { get; set; }

    public Nullable<int> Permission_Id { get; set; }

    public Nullable<int> Group_Id { get; set; }



    public virtual Group Group { get; set; }

    public virtual Permission Permission { get; set; }

}

}
