//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treatment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission_Group_Views
    {
        public string Group_Name_En { get; set; }
        public string Permission_Name_En { get; set; }
        public int Permission_Group_Id { get; set; }
    }
}
