//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treatment.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment_View
    {
        public int Treatment_Id { get; set; }
        public string Treatment_Subject { get; set; }
        public Nullable<System.DateTime> Treatment_Date { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string Treatment_Body { get; set; }
        public Nullable<bool> Required_Reply { get; set; }
        public Nullable<int> From_Employee_Structure_Id { get; set; }
        public Nullable<int> Treatment_Type_Id { get; set; }
        public Nullable<int> Treatment_Class_Id { get; set; }
        public Nullable<int> Treatment_Priority_id { get; set; }
        public Nullable<int> Treatment_Confidentiality_Id { get; set; }
        public Nullable<int> Treatment_Delivery_Id { get; set; }
        public Nullable<int> Treatment_Status_Id { get; set; }
        public Nullable<int> Treatment_Procedure_Id { get; set; }
        public Nullable<int> Prepared_Administration_Id { get; set; }
        public Nullable<System.DateTime> Required_Reply_Date { get; set; }
        public string Treatment_Number { get; set; }
        public string Employee_Name_Ar { get; set; }
        public string Employee_Name_En { get; set; }
    }
}
